class InternalError(Exception): 
	''' Raised when an internal error happens. '''
	pass